### ISSUE TITLE
Large queues allocated

### ISSUE THREAD

**Issue by mikehofm** [muckSponge/UnityAsync#2]
In ContinuationProcessor<T>, you allocate two arrays of size 500,000. This uses about 30 MB of memory for each type of IAwaitInstruction used (WaitForFrames, WaitForSeconds, etc), regardless of how few Continuations you actually use.

You could instead start the queue size small (like 16) and dynamically resize the arrays. For example:

```
public void Add(T cont)
{
	if (futureCount == futureQueue.Length)
	{
		int newLength = futureQueue.Length * 3 / 2;
		Array.Resize(ref futureQueue, newLength);
		Array.Resize(ref currentQueue, newLength);
	}

	// rest of method...
}
```

**Comment by muckSponge** [comment]
I've implemented queue resizing in 5430f351c9a06377d61018a946dcbb24c55418b4. Queue size starts at 1024 now. I'm happy to amend this to something smaller if you think that's too much. I think that ends up around 64KB per used IAwaitInstruction type.

**Comment by mikehofm** [comment]
I think you have a couple bugs in your commit. 
```
int newQueueSize = Math.Min(MaxQueueSize, futureQueue.Length);
```
Here you forgot the `* 3 / 2`, so you're just keeping it the same size.

The second bug is more subtle. In Process() you have:
```
if(!c.Evaluate())
{
	futureQueue[futureCount] = c;
	++futureCount;
}
```

It should be:
```
if(!c.Evaluate())
	Add(c);
```
Because Evaluate() may run the continuation, which may in turn add more items to futureQueue, and it can overflow. You could make Add() take a ref if you want to avoid copying the struct (and put ref parameters all the way up the call stack).

As for the initial size, I don't think you can go too wrong either way. You're balancing an insignificant amount of memory against an insignificant amount of time. On my machine, Array.Resize() takes about 1ms per 2MB of copying. So if, for example, someone were to do an `await Await.Seconds(60)` every tick at 60 fps, the queues would need to hold about 3600 items. If you start with a queue size of 2, and increase the size at a ratio of 1.5, you'll be copying a total of about 16000 items per queue (with a ratio of 1.5, you'll always end up copying about 3 times the final length of the queue, and the final length in this case will be 5395). At 64 bytes per item, that's about 1 ms between the two queues, over the course of a minute, compared to 0.32ms if you just set the queues to 5000 items up front. If you start the queues at 1000 items, it'll still take 82% as long as starting with 2 items, because all the big, slow copies happen after the queue gets large.

**Comment by muckSponge** [comment]
Thanks for the detailed analysis. Totally forgot the `* 3 / 2`, oops!

Regarding the second bug, my line of thought was a new `IAwaitInstruction` queued through the `ContinuationProcessor` is not really increasing the queue size; it's maintaining it (you need to "dequeue" a continuation before it can "enqueue" a new one. I'm trying to find a way to break it because in hindsight that assumption seems a little bit sketchy but thus far I haven't been able to. This includes using a very small initial count of 4 and creating an increasing number of coroutines (by invoking `async void` methods with `await Await.NextUpdate()`), and also a background context loop adding more frame awaiters every 500ms. The queue expands as expected but `futureCount` is never larger than the buffer, unless the exception is being swallowed somehow.

Also, regarding the `ref` idea, I thought `in` was semantically equivalent to `ref` so long as you don't call a method on the struct (which could mutate it). AFAIK at some point the struct must be copied because you can't `return ref this` from a struct method (which would be nice in `GetAwaiter`). The alternative is an extension method with a by ref parameter but that means every `await` must be on a variable (so something like `await Await.NextUpdate()` would have to become `var a = Await.NextUpdate(); await a;`).

**Comment by mikehofm** [comment]
> Also, regarding the ref idea, I thought in was semantically equivalent to ref

So actually, I didn't even notice you added the "in" keyword. It's been a few years since I've used C#, so my brain is still basically on C# 5. I didn't even realize they added that language feature, so I think my mind just edited it out. I'm glad to see it. I've gotten used to using `const FVector&` everywhere from Unreal Engine.

For the bug, the following should throw an IndexOutOfRangeException if you set your initial queue size to 2 and have no other awaiters:
```
void Start()
{
	UhOh();
	WaitSec(20);
	// queue now has [ WaitForSeconds(0), WaitForSeconds(20) ]
}

async void UhOh()
{
	await Await.Seconds(0);
	WaitSec(10);
	WaitSec(10);
	// Add two more items to the queue in the continuation. The new queue is now full. It
	// will next try to add the WaitForSeconds(20) past the end of the array.
}

async void WaitSec(float seconds)
{
	await Await.Seconds(seconds);
}
```

**Comment by muckSponge** [comment]
I tried your code but am unable to produce an exception. Let's decompose the code:
1. `UhOh()` is invoked: enqueues 1 awaiter (A) in update (count = 1)
2. `WaitSec(20)` is invoked, enqueues 1 awaiter (B) in update (count = 2)
3. A is dequeued (~0 seconds passed, we're in frame 2 now, count = 1)
4. `WaitSec(10)` is invoked twice, awaiters C and D are enqueued straight after each other (count = 3)

The count doesn't exceed 3 (I checked with debug statements). If an awaiter is evaluated and hasn't finished, it doesn't increase the queue size - it just gets pushed into the alternate buffer for the next frame (I call this `futureQueue`). If it *has* finished, it *doesn't* get pushed to the next frame buffer  and the count decreases. An awaiter cannot push another awaiter onto the buffer *unless* it has finished, because only a continuation can do that, and when this happens it does check the queue size.

To clarify, when I say "dequeue", I mean the awaiter is just not pushed to the next frame buffer.

```c#
public void Process()
{
	int count = futureCount;
	futureCount = 0;
					
	// swap queues
	var tmp = currentQueue;
	currentQueue = futureQueue;
	futureQueue = tmp;

	for(int i = 0; i < count; ++i)
	{
		ref var c = ref currentQueue[i];

		// we're just keeping this one in the queue
		if(!c.Evaluate())
		{
			futureQueue[futureCount] = c;
			++futureCount;
		}
	}
					
	Array.Clear(currentQueue, 0, count);
}
```

If we look at this code, we see `futureCount` is set to 0 before the awaiters are processed, so if an awaiter finishes and is not placed into the `futureQueue`, by default it is essentially reducing the count (`futureCount` is not incremented). All calls to `AwaitInstructionAwaiter<>.GetAwaiter` will invoke the appropriate `Add` method which does check the queue size.

Why reset `futureCount` instead of decrementing it when the awaiter is finished? It's more than just a count, it's an index into the end of the next frame buffer. This index would be incremented via `Add` and I suppose `Add` could be invoked from concurrent threads, which could cause issues but that's another (somewhat important...) problem.

**Comment by mikehofm** [comment]
It errors reliably for me. I'm not sure what the difference is. Did you set the initial queue size to 2?

Your steps aren't quite right. Or rather, they gloss over some important details.

Frame 1: (as you said) we enqueue WaitForSeconds(0), then WaitForSeconds(20)
Frame 2, in Process():

1. Start of first loop iteration: `futureCount` = 0, `i` = 0, `c` is WaitForSeconds(0)
2. Calls `c.Evaluate()`. Evaluate() ends up calling ContinuationProcessor.Add() twice, adding two WaitForSeconds(10), and then returns true. `futureCount` = 2.
3. Start of next iteration: `futureCount` = 2, `i` = 1. `c` = WaitForSeconds(20).
4. `c.Evaluate()` returns false. We try to do `futureQueue[2] = c`, which throws the out of range exception.

**Comment by muckSponge** [comment]
Not sure what's going on then. This is the only local change from last commit on master:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/5405629/63025671-0a3ff100-beed-11e9-9352-76ff0b1e74f4.png">

The other change is adding your test case (copied and pasted).

When I run it I do not get any kind of exception. If I add `Debug.Log(newQueueSize)` to `ContinuationProcessor.Add` inside the `if(futureCount == maxIndex)` block it prints out "3" but that's it.

**Comment by muckSponge** [comment]
Hol' up.

In frame 1, we add `WaitForSeconds(0)` (`futureCount` was 0, now 1). Still in frame 1, we add `WaitForSeconds(20)` (`futureCount == maxIndex` is `true`, queues resized to 3, `futureCount` was 1, now 2).

In frame 2 (`i` = 0), `WaitForSeconds(0).Evaluate()` adds two more `WaitForSeconds(10)` (`futureCount` = 2). At `i` = 1,`WaitForSeconds(20).Evaluate()` returns `false`, it is placed into `futureQueue[futureCount]`, which is still `2`, and `futureCount` is increased to 3. Queue capacity is 3 so this is valid.

In frame 3, none of the awaiters are finished so all 3 are added to `futureQueue`, capacity remains at 3.

...

Eventually they all finish and terminate, `futureCount` is 0, capacity is 3.

EDIT: I did manage to break it by adding another `WaitForSeconds` in LateUpdate frame 2. At this point `futureCount` is 3, which is more than `maxIndex`, causing it to bypass `if(futureCount == maxIndex)` and trying to access `futureQueue[3]`, which throws an exception. This exception was not being caught anywhere because LateUpdate returns immediately after the `await` keyword. I guess any exception thrown in an awaiter's `OnComplete` doesn't get caught. I'm updating the code to check for `futureCount >= maxIndex` and also finding a way to rethrow the exception elsewhere. Still not sure why you were seeing the exception and I wasn't.

**Comment by mikehofm** [comment]
Oh, I'm sorry. In Add(), I had changed `if (futureCount == maxIndex)` to `if (futureCount == futureQueue.Length)`. I forgot I did that. That explains the off-by-one difference.

So the revised code to crash it would be:
```
void Start()
{
	UhOh();
	WaitSec(20);
	WaitSec(20);
	// queue now has [ WaitForSeconds(0), WaitForSeconds(20), WaitForSeconds(20) ]
}

async void UhOh()
{
	await Await.Seconds(0);
	WaitSec(10);
	WaitSec(10);
	WaitSec(10);
}
```

This does throw an exception for me. It prints it in the Unity console if I don't have the debugger attached.

**Comment by muckSponge** [comment]
It throws an exception for me too. I've added a slightly more complex resize check in `Add` to avoid this. Basically, it considers how many awaiters are left in the current queue. Worst case all of them will need to be re-added so it resizes to ensure that if that is the case, there will be enough capacity for them. Not sure about whether to resize to 1.5x the largest potential queue size or 1.5x the current. I've done the latter but now I'm leaning toward the former (probably better to resize less frequently if it can be helped).

I went to all this trouble instead of calling `Add` inside `Process` because by their nature, these awaiters are likely to be evaluated over many frames. You'll typically have more awaiters active than awaiters being added in any one frame. As such, I wanted to keep the hot path in `Process` as lean as possible. This meant doing a bit more work in `Add`, which I hope is a good trade-off. I haven't benchmarked it though, I've found it really difficult to get reliable figures in the past.

I was thinking, for the threading issue where a background thread could call `Add` and manipulate the futureCount, instead of locking I could add a check to determine if it is called from in Unity's `SynchronizationContext` and if not, just await the `UnitySynchronizationContext`. A simple sync context comparison should be faster than a lock that's rarely needed, and it means I don't need to lock in `Process`.

**Comment by mikehofm** [comment]
Makes sense. If Add() is inlined, and just has a single extra `if (futureCount == maxIndex)` check, which evaluates to false 99% of the time and therefore plays nice with the branch predictors, I wouldn't expect much difference. But without profiling, I'm not sure.

I'm not sure how other people are using coroutines and async/await, but for me, I won't typically have more than a few dozen running at once. If I did for some reason want 100,000 active awaiters, I'd use a system that didn't run every update(). For example, WaitForFrames could use a priority queue (a heap), and WaitForSeconds could just use the built-in C# Timer. But I don't see many people needing this many awaiters.

I haven't thought about concurrency, but you could look into the .NET concurrent collections like [ConcurrentQueue<T>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentqueue-1?view=netframework-4.8). They're lock-free. You can also implement your own lock-free algorithms using the Interlocked class, but it's tricky to get right, and can introduce subtle bugs.

**Comment by muckSponge** [comment]
> For example, WaitForFrames could use a priority queue (a heap), and WaitForSeconds could just use the built-in C# Timer. But I don't see many people needing this many awaiters.

I originally opted for this unordered array approach to make it super easy to create your own awaiters for it. That said, I could probably introduce some more interfaces to allow a priority queue based approach for WaitForFrames and WaitForSeconds. I don't know enough about their implementations to understand whether I'd see performance benefits. From my understanding, it could be a O(n) operation to add a new awaiter to the queue, because it could mean pushing n items back. Likewise, removing a finished awaiter could mean pulling n items before it. I suppose the tradeoff is between ~constant per-frame overhead from evaluating n items every frame and occasional but larger per-frame overhead from reshuffling collections on queue/dequeue.

Bringing up the C# Timer (`System.Timers.Timer`) brings me onto another idea; we could offload much of the awaiter evaluation onto a background thread and post the continuation to the desired sync context when it is finished, freeing up the main thread. Wouldn't work for all awaiters because some require evaluation to occur in the `UnitySynchronizationContext`.

Then there's the job system. Haven't worked with it before but I think it allows jobs to run in parallel in Unity's sync context; perhaps this could be adapted to UnityAsync?

> I haven't thought about concurrency, but you could look into the .NET concurrent collections like [ConcurrentQueue](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentqueue-1?view=netframework-4.8). They're lock-free. You can also implement your own lock-free algorithms using the Interlocked class, but it's tricky to get right, and can introduce subtle bugs.

I went with a sync context awaiter on `Add` to resolve the concurrency issue. I know `Interlocked.Increment`, etc. exists but I'd have to introduce this into `Process` to work, which could impact on performance. I figured a simple check to see what context you're in would be faster than any more complicated concurrency business.

**Comment by mikehofm** [comment]
> I went with a sync context awaiter on Add to resolve the concurrency issue.

I think that makes sense, although again, I don't know that much about how async/await works, so don't take my word for it. The UnitySynchronizationContext.Post() call internally uses a lock, but I wouldn't worry about it unless you're planning on queuing up thousands of awaiters per second from background threads. Your hot path is fast.

> That said, I could probably introduce some more interfaces to allow a priority queue based approach for WaitForFrames and WaitForSeconds.

I don't recommending you implement these. You're doing the right thing by keeping things simple. Unless you have users that actually want to have huge numbers of active awaiters, the performance benefits will go unnoticed.

However, purely for interest, I'll talk a bit about how you might do this. 

A priority queue and a heap are essentially the same thing. A priority queue would be the abstract notion of a queue where each item has a priority and high-priority items are dequeued first, while a heap is the data structure you'd use to implement a priority queue. Similar idea as a map or dictionary vs a hash table; hash table is the implementation.

In a classic binary heap Peek() is O(1) and Insert() and Dequeue() are O(log(n)). If you use a fancy schmancy Fibonacci heap, Insert() is also O(1) amortized. So you'd pay a small O(log(n)) cost whenever a WaitForFrames completes and is removed. You could basically have as many awaiters as will fit in memory with negligible performance impact.

A priority queue is only applicable if you can assign each item a priority. That works for WaitForFrames or WaitForSeconds, but won't work with WaitWhile.

For WaitForSeconds I mentioned the Timer class simply because it already exists, is easy to use, and is efficient. No need to mess with priority queues.

As a side note, the `Queue<T>` class will have O(1) enqueue (amortized) and dequeue. It would be implemented internally as a circular array. It's only useful if you only ever need enqueue stuff at the end, so it doesn't really apply here.

Unity's Job system doesn't really let you do anything that might be unsafe. The only shared memory you can reference from a Job are `NativeArray<T>` instances and the other native containers built on NativeArray. NativeArray has a bunch of safety checks (only in editor though, not in the standalone game) that protect against possible race conditions. They don't run in the UnitySynchronizationContext. They're useful when you need to do some heavy computations that don't need to reference anything (or rather, anything other than native containers).

**Comment by muckSponge** [comment]
> A priority queue is only applicable if you can assign each item a priority. That works for WaitForFrames or WaitForSeconds, but won't work with WaitWhile.

I was thinking something like...
```c#
interface IPriorityAwaitInstruction<T> where T : IComparable<T>
{
	public T Priority { get; }
}
```
... for instructions which could be assigned a priority (and an accompanying priority queue processor), and keeping `IAwaitInstruction` for others but that's getting into over-engineered territory. I originally thought returning an int would be fine but that's not going to play too nicely with something like `WaitForSeconds`.

I'm going to close this issue because we've fixed it but thanks for your feedback and discussion on the other points :)
